name: Build and run unit test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
 
    steps:      
    - name: Install Intel MKL
      run: |
           wget https://registrationcenter-download.intel.com/akdlm/irc_nas/tec/16903/l_mkl_2020.3.279.tgz
           tar -zxvf l_mkl_2020.3.279.tgz
           cd l_mkl_2020.3.279
           
           echo "ACCEPT_EULA=accept" >> silent.cfg
           echo "PSET_INSTALL_DIR=/opt/intel" >> silent.cfg
           sudo bash ./install.sh --user-mode -s ./silent.cfg
           
           export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/intel/lib/intel64/
           
           cd ..
           
    - name: Build libqpsolver
      run: |
           git clone https://github.com/shengwen-tw/libqpsolver.git
           cd libqpsolver
           make
      
    - name: Run example
      run: |
           MKL_LIB_PATH=/opt/intel/mkl/lib/intel64/
           MKL_LIBS=$MKL_LIB_PATH/libmkl_def.so
           MKL_LIBS=$MKL_LIBS:$MKL_LIB_PATH/libmkl_avx2.so
           MKL_LIBS=$MKL_LIBS:$MKL_LIB_PATH/libmkl_core.so
           MKL_LIBS=$MKL_LIBS:$MKL_LIB_PATH/libmkl_intel_lp64.so
           MKL_LIBS=$MKL_LIBS:$MKL_LIB_PATH/libmkl_sequential.so
           export LD_PRELOAD=$MKL_LIBS
           
    - name: Run unit test
      run: |
          pip3 install pybind11
          cd libqpsolver
          make unit_test
